"""add follow functionality

Revision ID: 800df44681d9
Revises: 9f0066c0abbb
Create Date: 2019-05-12 03:42:54.626173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800df44681d9'
down_revision = '9f0066c0abbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
